import { RULE_SET_VERSION, type RedFlagRule } from '../types';
import { GLUCOSE, PULSE, RR, SYS } from './cardio-respiratory';

const STARTER_SOURCE = 'curated starter set, requires clinical review (debt TD-06)';

export const BLEEDING_HAEMODYNAMIC_RULES: readonly RedFlagRule[] = [
  {
    identifier: 'GI_BLEEDING_001',
    description: 'Vomiting blood, black stools or blood in stool',
    trigger: { hasSymptomAny: ['MK-SYM-042', 'MK-SYM-043', 'MK-SYM-046'] },
    evidenceRequired: ['MK-SYM-042'],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'Upper or lower GI bleeding can decompensate quickly.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HAEMATURIA_001',
    description: 'Blood in urine',
    trigger: { hasSymptom: 'MK-SYM-051' },
    evidenceRequired: ['MK-SYM-051'],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Haematuria needs infection, stone and malignancy considered.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'OLIGURIA_001',
    description: 'Reduced urine output',
    trigger: { hasSymptom: 'MK-SYM-052' },
    evidenceRequired: ['MK-SYM-052'],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Falling output can indicate dehydration, sepsis or kidney injury.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'ANAEMIA_SEVERE_001',
    description: 'Haemoglobin flagged critically low',
    trigger: { labFlaggedLow: 'MK-LAB-001' },
    evidenceRequired: ['MK-LAB-001'],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Severe anaemia needs a cause found and transfusion considered.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPOTENSION_001',
    description: 'Systolic blood pressure below 90 mmHg',
    trigger: { vitalBelow: { code: SYS, value: 90 } },
    evidenceRequired: [SYS],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'Hypotension may indicate shock from any cause.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPOTENSION_002',
    description: 'Systolic blood pressure below 100 mmHg',
    trigger: { vitalBelow: { code: SYS, value: 100 } },
    evidenceRequired: [SYS],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Low-normal systolic pressure deserves review before it deteriorates.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPERTENSIVE_URGENCY_001',
    description: 'Systolic blood pressure at or above 180 mmHg',
    trigger: { vitalAbove: { code: SYS, value: 180 } },
    evidenceRequired: [SYS],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Severe hypertension needs end-organ assessment even when asymptomatic.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'TACHYCARDIA_001',
    description: 'Pulse above 120 beats per minute',
    trigger: { vitalAbove: { code: PULSE, value: 120 } },
    evidenceRequired: [PULSE],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Marked tachycardia needs a cause found: sepsis, blood loss, thyrotoxicosis.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'BRADYCARDIA_001',
    description: 'Pulse below 50 beats per minute',
    trigger: { vitalBelow: { code: PULSE, value: 50 } },
    evidenceRequired: [PULSE],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Bradycardia can indicate conduction disease or drug effect.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'TACHYPNOEA_001',
    description: 'Respiratory rate above 24 per minute',
    trigger: { vitalAbove: { code: RR, value: 24 } },
    evidenceRequired: [RR],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'A raised respiratory rate is an early warning sign of deterioration.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPERGLYCAEMIA_CRITICAL_001',
    description: 'Blood glucose at or above 400 mg/dL',
    trigger: { vitalAbove: { code: GLUCOSE, value: 400 } },
    evidenceRequired: [GLUCOSE],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'Critical hyperglycaemia risks ketoacidosis and hyperosmolar states.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPERGLYCAEMIA_001',
    description: 'Blood glucose at or above 250 mg/dL',
    trigger: { vitalAbove: { code: GLUCOSE, value: 250 } },
    evidenceRequired: [GLUCOSE],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Marked hyperglycaemia needs treatment review.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPOGLYCAEMIA_CRITICAL_001',
    description: 'Blood glucose below 54 mg/dL',
    trigger: { vitalBelow: { code: GLUCOSE, value: 54 } },
    evidenceRequired: [GLUCOSE],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'Severe hypoglycaemia is immediately dangerous and treatable.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPOGLYCAEMIA_001',
    description: 'Blood glucose below 70 mg/dL',
    trigger: { vitalBelow: { code: GLUCOSE, value: 70 } },
    evidenceRequired: [GLUCOSE],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Hypoglycaemia needs fast-acting carbohydrate and a cause found.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
];