/**
 * Neurological and infection red-flag rules.
 */

import { RULE_SET_VERSION, type RedFlagRule } from '../types';
import { DIA, GLUCOSE, PULSE, RR, SYS, TEMP } from './cardio-respiratory';

const STARTER_SOURCE = 'curated starter set, requires clinical review (debt TD-06)';

export const NEURO_INFECTION_RULES: readonly RedFlagRule[] = [
  {
    identifier: 'STROKE_SCREEN_001',
    description: 'Focal neurological deficit',
    trigger: { hasSymptom: 'MK-SYM-033' },
    evidenceRequired: ['MK-SYM-033'],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'A focal deficit is a stroke until proven otherwise; time is brain.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'STROKE_SCREEN_002',
    description: 'Sudden severe headache with neck stiffness',
    trigger: { all: [{ hasSymptom: 'MK-SYM-031' }, { hasSymptom: 'MK-SYM-032' }] },
    evidenceRequired: ['MK-SYM-031', 'MK-SYM-032'],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale:
      'Thunderclap headache with neck stiffness raises subarachnoid and meningitic risk.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'STROKE_SCREEN_003',
    description: 'Sudden severe headache with focal deficit',
    trigger: { all: [{ hasSymptom: 'MK-SYM-031' }, { hasSymptom: 'MK-SYM-033' }] },
    evidenceRequired: ['MK-SYM-031', 'MK-SYM-033'],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'Sudden maximal headache with a deficit indicates a vascular event.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'SEIZURE_001',
    description: 'Seizure reported',
    trigger: { hasSymptom: 'MK-SYM-034' },
    evidenceRequired: ['MK-SYM-034'],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'A witnessed seizure needs assessment for cause, injury and recurrence risk.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'MENINGITIS_001',
    description: 'Fever with neck stiffness',
    trigger: { all: [{ hasSymptom: 'MK-SYM-020' }, { hasSymptom: 'MK-SYM-032' }] },
    evidenceRequired: ['MK-SYM-020', 'MK-SYM-032'],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'The fever plus neck-stiffness combination is the meningitis screen.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'SEPSIS_SCREEN_001',
    description: 'Fever with tachycardia and tachypnoea',
    trigger: {
      all: [
        { hasSymptom: 'MK-SYM-020' },
        { vitalAbove: { code: PULSE, value: 100 } },
        { vitalAbove: { code: RR, value: 22 } },
      ],
    },
    evidenceRequired: ['MK-SYM-020', PULSE, RR],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'Fever with systemic signs is the sepsis pattern this rule exists to catch early.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'SEPSIS_SCREEN_002',
    description: 'Fever with tachycardia',
    trigger: { all: [{ hasSymptom: 'MK-SYM-020' }, { vitalAbove: { code: PULSE, value: 100 } }] },
    evidenceRequired: ['MK-SYM-020', PULSE],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Fever with a fast pulse warrants review even before full sepsis criteria.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'FEVER_HIGH_001',
    description: 'Temperature at or above 39 Celsius',
    trigger: { vitalAbove: { code: TEMP, value: 39 } },
    evidenceRequired: [TEMP],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'High fever needs a cause found promptly.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HYPOTHERMIA_001',
    description: 'Temperature below 35 Celsius',
    trigger: { vitalBelow: { code: TEMP, value: 35 } },
    evidenceRequired: [TEMP],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'Hypothermia indicates exposure or critical illness.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'NEURO_DETERIORATION_001',
    description: 'Confusion reported',
    trigger: { hasSymptom: 'MK-SYM-036' },
    evidenceRequired: ['MK-SYM-036'],
    severity: 'AMBER',
    action: 'PRIORITY_CLINICIAN_REVIEW',
    clinicalRationale: 'New confusion can indicate sepsis, hypoglycaemia, stroke or intoxication.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
  {
    identifier: 'HAEMOPTYSIS_001',
    description: 'Coughing blood',
    trigger: { hasSymptom: 'MK-SYM-008' },
    evidenceRequired: ['MK-SYM-008'],
    severity: 'RED',
    action: 'IMMEDIATE_HUMAN_TRIAGE',
    clinicalRationale: 'Haemoptysis always requires a cause to be found, and TB is endemic.',
    source: STARTER_SOURCE,
    version: RULE_SET_VERSION,
  },
];