/**
 * Symptom vocabulary — gastrointestinal, genitourinary, musculoskeletal and skin presentations.
 */

import type { ClinicalConcept } from '../concept';
import { symptom } from './symptoms-cardiorespiratory';

export const GI_GU_SYMPTOMS: readonly ClinicalConcept[] = [
  symptom(
    'MK-SYM-040',
    'Abdominal pain',
    'GASTROINTESTINAL',
    [
      'abdominal pain',
      'stomach pain',
      'belly pain',
      'tummy pain',
      'pain in abdomen',
      'pet dard',
      'pet mein dard',
      'पेट दर्द',
      'पोट दुखणे',
      'પેટમાં દુખાવો',
      'வயிற்று வலி',
      'పొట్ట నొప్పి',
      'পেট ব্যথা',
    ],
    { pathways: ['PATH-ABDOMINAL-PAIN'], redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-041',
    'Vomiting',
    'GASTROINTESTINAL',
    ['vomiting', 'vomited', 'throwing up', 'nausea', 'ulti', 'उल्टी', 'ओकारी', 'વાંતિ'],
    { pathways: ['PATH-ABDOMINAL-PAIN', 'PATH-FEVER'] },
  ),
  symptom(
    'MK-SYM-042',
    'Vomiting blood',
    'GASTROINTESTINAL',
    ['vomiting blood', 'blood in vomit', 'haematemesis', 'khoon wali ulti', 'खून वाली उल्टी', 'रक्ताची ओकारी'],
    { pathways: ['PATH-ABDOMINAL-PAIN'], redFlagRelevant: true, potentiallyEmergent: true },
  ),
  symptom(
    'MK-SYM-043',
    'Black stools',
    'GASTROINTESTINAL',
    ['black stools', 'black motion', 'tarry stools', 'melaena', 'kala pakhana', 'काला पखाना', 'काळी शौच'],
    { pathways: ['PATH-ABDOMINAL-PAIN'], redFlagRelevant: true, potentiallyEmergent: true },
  ),
  symptom(
    'MK-SYM-044',
    'Diarrhoea',
    'GASTROINTESTINAL',
    ['diarrhoea', 'diarrhea', 'loose motions', 'watery stools', 'dast', 'जुलाब', 'झाडा', 'পাতলা পায়খানা'],
    { pathways: ['PATH-ABDOMINAL-PAIN', 'PATH-FEVER'], redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-045',
    'Constipation',
    'GASTROINTESTINAL',
    ['constipation', 'hard stools', 'not passing stools', 'kabz', 'कब्ज़', 'बद्धकोष्ठ'],
    { pathways: ['PATH-ABDOMINAL-PAIN'] },
  ),
  symptom(
    'MK-SYM-046',
    'Blood in stool',
    'GASTROINTESTINAL',
    ['blood in stool', 'blood in motion', 'bleeding per rectum', 'khoon wala pakhana', 'मल में खून'],
    { pathways: ['PATH-ABDOMINAL-PAIN'], redFlagRelevant: true, potentiallyEmergent: true },
  ),
  symptom(
    'MK-SYM-047',
    'Heartburn or reflux',
    'GASTROINTESTINAL',
    ['heartburn', 'acidity', 'acid reflux', 'seene mein jalan', 'khatta dakaar', 'एसिडिटी', 'छाती में जलन'],
    { pathways: ['PATH-ABDOMINAL-PAIN', 'PATH-CHEST-PAIN'] },
  ),
  symptom(
    'MK-SYM-048',
    'Abdominal distension',
    'GASTROINTESTINAL',
    ['abdominal distension', 'bloating', 'swollen abdomen', 'pet phoolna', 'पेट फूलना', 'पोट फुगणे'],
    { pathways: ['PATH-ABDOMINAL-PAIN'] },
  ),
  symptom(
    'MK-SYM-050',
    'Burning urination',
    'GENITOURINARY',
    ['burning urination', 'burning micturition', 'painful urination', 'dysuria', 'peshab mein jalan', 'पेशाब में जलन', 'लघवी करताना जळजळ'],
    { pathways: ['PATH-FEVER'], redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-051',
    'Blood in urine',
    'GENITOURINARY',
    ['blood in urine', 'haematuria', 'hematuria', 'red urine', 'peshab mein khoon', 'पेशाब में खून'],
    { redFlagRelevant: true, potentiallyEmergent: true },
  ),
  symptom(
    'MK-SYM-052',
    'Reduced urine output',
    'GENITOURINARY',
    ['reduced urine output', 'passing less urine', 'not passing urine', 'oliguria', 'peshab kam aa raha', 'पेशाब कम आना'],
    { redFlagRelevant: true, potentiallyEmergent: true },
  ),
  symptom(
    'MK-SYM-053',
    'Vaginal bleeding in pregnancy',
    'GENITOURINARY',
    ['vaginal bleeding', 'bleeding in pregnancy', 'गर्भावस्था में रक्तस्राव'],
    { pathways: ['PATH-SPECIAL-POPULATIONS'], redFlagRelevant: true, potentiallyEmergent: true },
  ),
  symptom(
    'MK-SYM-054',
    'Excessive thirst',
    'ENDOCRINE',
    ['excessive thirst', 'always thirsty', 'polydipsia', 'zyada pyaas', 'अधिक प्यास', 'जास्त तहान'],
    { pathways: ['PATH-CHRONIC-DISEASE'], redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-055',
    'Frequent urination',
    'GENITOURINARY',
    ['frequent urination', 'passing urine often', 'polyuria', 'baar baar peshab', 'बार बार पेशाब', 'वारंवार लघवी'],
    { pathways: ['PATH-CHRONIC-DISEASE'], redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-060',
    'Joint pain',
    'MUSCULOSKELETAL',
    ['joint pain', 'arthralgia', 'knee pain', 'jodon mein dard', 'जोड़ों में दर्द', 'सांधेदुखी'],
    { pathways: ['PATH-CHRONIC-DISEASE'] },
  ),
  symptom(
    'MK-SYM-061',
    'Joint swelling',
    'MUSCULOSKELETAL',
    ['joint swelling', 'swollen joint', 'jodon mein sujan', 'जोड़ों में सूजन', 'सांधे सुजणे'],
    { redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-062',
    'Back pain',
    'MUSCULOSKELETAL',
    ['back pain', 'lower back pain', 'kamar dard', 'कमर दर्द', 'पाठ दुखणे'],
    { pathways: ['PATH-CHRONIC-DISEASE'] },
  ),
  symptom(
    'MK-SYM-063',
    'Swelling of legs',
    'CARDIOVASCULAR',
    ['leg swelling', 'swollen feet', 'pedal oedema', 'pedal edema', 'paon mein sujan', 'पैरों में सूजन', 'पाय सुजणे'],
    { pathways: ['PATH-CHEST-PAIN'], redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-064',
    'Rash',
    'DERMATOLOGICAL',
    ['rash', 'skin rash', 'red spots', 'itching', 'khujli', 'daane', 'चकत्ते', 'खुजली'],
    { pathways: ['PATH-FEVER'], redFlagRelevant: true },
  ),
  symptom(
    'MK-SYM-065',
    'Non-healing wound',
    'DERMATOLOGICAL',
    ['non healing wound', 'ulcer not healing', 'chronic ulcer', 'ghav nahi bharta', 'घाव नहीं भरता', 'जखम भरत नाही'],
    { pathways: ['PATH-CHRONIC-DISEASE'], redFlagRelevant: true },
  ),
];